### ISSUE TITLE
Draw graphs of the throughput of the consumer

### ISSUE THREAD

**Issue by goodluckz** [caramucho/ndn-mrbart#5]

**Comment by caramucho** [comment]
![figure_11](https://user-images.githubusercontent.com/4201194/34704770-c331345a-f53e-11e7-8b5e-f36304a48560.png)

**Comment by goodluckz** [comment]
![figure_12](https://user-images.githubusercontent.com/4201194/34704835-5d51f7ae-f53f-11e7-9dd0-2d7da21845c2.png)

**Comment by caramucho** [comment]
![figure_13](https://user-images.githubusercontent.com/4201194/34704892-d4bb42d2-f53f-11e7-9c6e-66189824cc5a.png)

**Comment by goodluckz** [comment]
![figure_14](https://user-images.githubusercontent.com/4201194/34705161-b87847bc-f541-11e7-873a-f6a4b70e3a21.png)

**Comment by goodluckz** [comment]
![figure_13](https://user-images.githubusercontent.com/4201194/34705203-1f83e2ae-f542-11e7-9957-d017b954176d.png)
